# Reference: https://www.appveyor.com/docs/appveyor-yml/
install:
  - ps: Write-Host 'Installing Unity 5.3.1 via Chocolatey'
  #- cinst unity --version 5.3.1
  - ps: .\BuildScripts\installUnity.ps1
  - ps: Write-Host 'Done installing Unity'
  
  https://download.unity3d.com/download_unity/cc9cbbcc37b4/Windows64EditorInstaller/UnitySetup64-5.3.1f1.exe
          http://netstorage.unity3d.com/unity/cc9cbbcc37b4/Windows64EditorInstaller/UnitySetup64-5.3.1f1.exe